### ISSUE TITLE
[Question]: A driver code for WsClient

### ISSUE THREAD

**Issue by eslam-ahmed-khair** [WebRTSP/ReStreamer#1]
Hello,

I am trying to create a driver code using `WsClient` and `GstClient` as its `WebRTCPeer`, that is having gstreamer-based WebRTC client instead of the Web Browser. I also noticed that `WsClient` is missing an override for `GstWebRTCPeer`'s `virtual void prepare()` so I added an empty override for now.

so I wrote the following small piece of code:

```
#include <CxxPtr/GlibPtr.h>
#include <CxxPtr/libwebsocketsPtr.h>
#include <RtcStreaming/GstRtcStreaming/GstClient.h>

#include <iostream>

#include "ClientSession.h"
#include "WsClient.h"

static std::unique_ptr<WebRTCPeer> CreateClientPeer() { return std::make_unique<GstClient>(); }

static std::unique_ptr<ClientSession> CreateSession(
    const std::function<void(const rtsp::Request*) noexcept>& sendRequest,
    const std::function<void(const rtsp::Response*) noexcept>& sendResponse) noexcept {
  return std::make_unique<ClientSession>(std::bind(CreateClientPeer), sendRequest, sendResponse);
}

static void disconnected() { std::cout << "disconnected!" << std::endl; }

int main() {
  client::Config conf = {"localhost", 5554};

  GMainContextPtr contextPtr(g_main_context_new());
  GMainContext* context = contextPtr.get();
  g_main_context_push_thread_default(context);

  GMainLoopPtr loopPtr(g_main_loop_new(context, FALSE));
  GMainLoop* loop = loopPtr.get();

  client::WsClient ws_client(conf, loop, CreateSession, disconnected);

  ws_client.init();
  ws_client.connect();

  return 0;
}

```

I launch `ReStreamer`, then I execute my code and I get the following:
```
[2021/05/24 11:51:21:5816] N: LWS: 4.1.7-39e8932, loglevel 7
[2021/05/24 11:51:21:5816] N: NET CLI SRV H1 H2 WS IPv6-absent
[2021/05/24 11:51:21:5817] N:    /usr/local/lib/libwebsockets-evlib_glib.so
[2021-05-24 11:51:21.582] [WsClient] [info] Connecting to localhost:5554...
[2021-05-24 11:51:21.582] [WsClient] [error] Can not connect to server.
disconnected!
```

I'm no expert in `libwebsocket` so there could be something I am missing here.

**Comment by RSATom** [comment]
You can find basic client example at https://github.com/WebRTSP/Native/blob/master/Apps/Test/Test.cpp Just change `#define ENABLE_SERVER 1` to `#define ENABLE_SERVER 0`

**Comment by eslam-ahmed-khair** [comment]
@RSATom Thanks for your quick response and pointing this out.

Looks like I forgot to spin the main loop and I also did not pass a `uri` to the constructor of `ClientSession` which I thought to be an `RTSP` stream but it rather represents a media name for the server to describe such as:

```
static std::unique_ptr<ClientSession> CreateSession(
    const std::function<void(const rtsp::Request*) noexcept>& sendRequest,
    const std::function<void(const rtsp::Response*) noexcept>& sendResponse) noexcept {
  return std::make_unique<ClientSession>("Office%20Camera2", std::bind(CreateClientPeer), sendRequest,
                                         sendResponse);
}
```
whereas the server config in this case should have the following line
`{name: "Office Camera2",               url: "rtsp://admin:admin@192.168.0.201/defaultPrimary?streamType=u",                          description: "Office Camera2"}`

Then I encountered the following error:
```
Client_exe: ReStreamer/WebRTSP/RtcStreaming/GstRtcStreaming/GstWebRTCPeer.cpp:397: virtual void GstWebRTCPeer::addIceCandidate(unsigned int, const string&): Assertion `_rtcbinPtr' failed.
```
This is because `GstClient::addIceCandidate` was using the base class (`GstWebRTCPeer`) method as an override and that pointer was never allocated. So I replaced the implementation of `GstClient::addIceCandidate` with an exact one of the base class but using the proper pointer which is `_p->rtcbinPtr` in this case. Then it worked like a charm.

Thank you for your efforts!

**Comment by RSATom** [comment]
Yes, `ClientSession` gets some abstract string as `uri` which meaning can understand only server. It can be some extern url (for example if you want to have some sort of url restreamer) or some fixed string specified in server config.

**Comment by RSATom** [comment]
@eslam-ahmed-khair I've checked `GstClient` sources and think you don't need to override `addIceCandidate` there. All required job happens here: https://github.com/WebRTSP/RtStreaming/blob/master/GstRtStreaming/GstClient.cpp#L65

**Comment by RSATom** [comment]
@eslam-ahmed-khair is it possible you are just used outdated sources?

**Comment by RSATom** [comment]
@eslam-ahmed-khair now I'm pretty sure you are using outdated version
```
#include <RtcStreaming/GstRtcStreaming/GstClient.h>
```
`RtcStreaming` and `GstRtcStreaming` was renamed to `RtStreaming` and `GstRtStreaming` respectively

**Comment by eslam-ahmed-khair** [comment]
yep, I was on this commit [11b5d17](https://github.com/WebRTSP/ReStreamer/commit/11b5d1786931a56ddc05433aa3427a0ea0443eba).

Thanks for checking it out!
Best Regards
