### ISSUE TITLE
GST_TRACER reporting object-alive

### ISSUE THREAD

**Issue by eslam-ahmed-khair** [WebRTSP/ReStreamer#12]
Kindly, find GST_TRACER report on that:

```
0:00:52.045228005 37407 0x56172a058e60 TRACE             GST_TRACER :0:: object-alive, type-name=(string)GstBus, address=(gpointer)0x561729ecc3e0, description=(string)<bus1>, ref-count=(uint)1, trace=(string);
0:00:52.045248874 37407 0x56172a058e60 TRACE             GST_TRACER :0:: object-alive, type-name=(string)GstMessage, address=(gpointer)0x56172a493380, description=(string)application message: 0x56172a493380, time 99:99:99.999999999, seq-num 1277, element 'tee0', tee-pad-removed;, ref-count=(uint)1, trace=(string);
0:00:52.045258552 37407 0x56172a058e60 TRACE             GST_TRACER :0:: object-alive, type-name=(string)GstMessage, address=(gpointer)0x56172a493100, description=(string)application message: 0x56172a493100, time 99:99:99.999999999, seq-num 1276, element 'tee0', tee-pad-removed;, ref-count=(uint)1, trace=(string);
```

I wanted to see their stack traces, I used `GST_DEBUG="GST_TRACER:7" GST_TRACERS="leaks(stack-traces-flags=full)"` for that, but still no line numbers showing only addresses. My build is debug and I also tried using the env variable `GST_LEAKS_TRACER_STACK_TRACE`.

**Comment by eslam-ahmed-khair** [comment]
Okay, those are fixed but I am faced with something new.

After terminating my app I get the following:
`(webrtc-streaming:53812): GStreamer-CRITICAL **: 10:12:52.764: gst_element_set_state: assertion 'GST_IS_ELEMENT (element)' failed`

now this was a really stroke of luck catching its stackstrace:
```
#3  0x00007ffff6f2f77a in gst_element_set_state () at /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#4  0x00007ffff7ca31c2 in GstStreamingSource::cleanup() (this=0x555555f38600)
    at /home/dev/Repos/webrtc-streaming.new/src/webrtc-streamer/submodules/WebRTSP/RtStreaming/GstRtStreaming/GstStreamingSource.cpp:155
#5  0x00007ffff7ca2645 in GstStreamingSource::~GstStreamingSource() (this=0x555555f38600, __in_chrg=<optimized out>)
    at /home/dev/Repos/webrtc-streaming.new/src/webrtc-streamer/submodules/WebRTSP/RtStreaming/GstRtStreaming/GstStreamingSource.cpp:20
```
This stacktrace can only be made available when you explicitly clear the `MountPoints`.

Now the fix seems easy, just set the pipeline's state to `NULL` only if there is one, you already have the if condition ready `gst_element_set_state(pipeline, GST_STATE_NULL);`.

**Comment by RSATom** [comment]
Yes, I've thought about possibility of such issue right before your message :smile:

**Comment by eslam-ahmed-khair** [comment]
Can't Thank you enough!

**Comment by RSATom** [comment]
@eslam-ahmed-khair please try now

**Comment by eslam-ahmed-khair** [comment]
> @eslam-ahmed-khair please try now

Fixed!
