### ISSUE TITLE
On the fly transcoding

### ISSUE THREAD

**Issue by rbr-goodrich** [WebRTSP/ReStreamer#14]
Hello,

Since webRTSP does not support H265 I'm attempting on the fly transcoding for my IP cameras that only emit h265 feeds, from h265 to h264.

Everything compiles fine, and h264 feeds still work, however the pipeline refuses to link, and provideds these errors when attempting the h265 transcode. 

```

(<unknown>:18870): GLib-GObject-WARNING **: 21:43:38.720: ../../../../gobject/gsignal.c:2524: signal
'on-negotiation-needed' is invalid for instance '0x7f4c062890' of type 'GstRtpH264Pay'

(<unknown>:18870): GLib-GObject-WARNING **: 21:43:38.720: ../../../../gobject/gsignal.c:2524: signal
'on-ice-candidate' is invalid for instance '0x7f4c062890' of type 'GstRtpH264Pay'

(<unknown>:18870): GLib-GObject-WARNING **: 21:43:38.720: ../../../../gobject/gsignal.c:3493: signal
name 'get-transceivers' is invalid for instance '0x7f4c062890' of type 'GstRtpH264Pay'


```
Here is the code i've added.

```
/* in GstReStreamer.h */

    /* in   class GstReStreamer : public GstWebRTCPeer { private: */
    GstCapsPtr _h265CapsPtr;

/* in GstReStreamer.cpp */

    /* in GstReStreamer::prepare */

    _h264CapsPtr.reset(gst_caps_from_string("video/x-h264"));
    _vp8CapsPtr.reset(gst_caps_from_string("video/x-vp8"));
    _h265CapsPtr.reset(gst_caps_from_string("video/x-h265"));

    GstCapsPtr supportedCapsPtr(gst_caps_copy(_h264CapsPtr.get()));
    gst_caps_append(supportedCapsPtr.get(), gst_caps_copy(_vp8CapsPtr.get()));
    gst_caps_append(supportedCapsPtr.get(), gst_caps_copy(_h265CapsPtr.get()));


    /* in  GstReStreamer::srcPadAdded */
   else if(gst_caps_is_always_compatible(caps, _h265CapsPtr.get())) {
          GstElement* out =
              gst_parse_bin_from_description(
                  "nvvideoconvert ! queue ! nvv4l2h264enc ! h264parse config-interval=-1 ! rtph264pay pt=96"
                  "webrtcbin name=srcrtcbin",
                  TRUE, NULL);
          gst_bin_add(GST_BIN(pipeline), out);
          gst_element_sync_state_with_parent(out);
  
          GstPad *sink = (GstPad*)out->sinkpads->data;
  
          if(GST_PAD_LINK_OK != gst_pad_link(pad, sink))
              assert(false);
  }

```

Im assuming that uridecodebin emits a decoded h265 feed, so it should be able to be linked to nvvideoconvert. 

I use nvvideoconvert and nvv4l2h264enc as i have an nvidia gpu and can accelerate the transcoding. You can switch these elements out with videoconvert, gstomxh264enc/x264enc. The issue will still be the same.

Do you have any advice ?

**Comment by RSATom** [comment]
You are missing ` ! ` at the end of `nvvideoconvert ! queue ! nvv4l2h264enc ! h264parse config-interval=-1 ! rtph264pay pt=96`, so for `gst_parse_bin_from_description` your pipeline looks like
`nvvideoconvert ! queue ! nvv4l2h264enc ! h264parse config-interval=-1 ! rtph264pay pt=96webrtcbin name=srcrtcbin`

**Comment by rbr-goodrich** [comment]
whoops, sorry for the inconvenience. I should've caught that. 

Sometimes the smallest things can easily be overlooked.  :man_shrugging:
