### ISSUE TITLE
webrtc clients failing to connect breaks running streaming session for already running clients 

### ISSUE THREAD

**Issue by eslam-ahmed-khair** [WebRTSP/ReStreamer#19]
Hello,

Whenever a successful webrtc connection is established, a trace log like this appears:
`Connection State changed: "GST_WEBRTC_PEER_CONNECTION_STATE_NEW"`

Now when other clients result in `Connection State changed: "GST_WEBRTC_PEER_CONNECTION_STATE_FAILED"`, because peer to peer connection couldn't be established (for some reason), this breaks the running streaming session for the already connected clients and their stream just hangs on the web. At this state, `ReStreamer` must be restarted to allow future connections as it is stuck otherwise.

**Comment by RSATom** [comment]
Please try the latest version

**Comment by eslam-ahmed-khair** [comment]
@RSATom Fixed, Thank you!

How were you able to discover that the queue of a broken peer is the cause of it? :)

FYI, I noticed that a small memory fingerprint is left over off of those broken clients. it's about ~1 MiB leaked per broken client.

**Comment by RSATom** [comment]
> How were you able to discover that the queue of a broken peer is the cause of it? :)

I just forgot one downstream brunch which can't consume buffers by some reasons will lead to stop whole pipeline... It's very obvious if remember about it....

**Comment by RSATom** [comment]
> FYI, I noticed that a small memory fingerprint is left over off of those broken clients. it's about ~1 MiB leaked per broken client.

Are you sure it's not recoverable memory allocation? If not, please create another issue.
