### ISSUE TITLE
Problem with Stream

### ISSUE THREAD

**Issue by georgek5git** [WebRTSP/ReStreamer#2]
Hello,

From yesterday i have problem with my stream. Stream also has a problem here: http://ipcam.stream:5080/
Is the problem from central server? If yes, How long will it take to repair it?
Thanks!

Giorgos

**Comment by RSATom** [comment]
Yes, there was problem with `ipcam.stream` server and it was restarted. But I don't understand how it can affect your server.

**Comment by georgek5git** [comment]
Your stream has problem again. In my server has libraries from other server , am i right?

**Comment by georgek5git** [comment]
Ok, thank you! You are clear!

**Comment by RSATom** [comment]
@georgek5git please close this issue if you don't have another questions.

**Comment by georgek5git** [comment]
ok
