### ISSUE TITLE
Unreachable RTSP streams causes ReStreamer to get stuck

### ISSUE THREAD

**Issue by eslam-ahmed-khair** [WebRTSP/ReStreamer#22]
Hello,

if a client requests an RTSP stream that is unreachable at the moment, `ReStreamer` will hang for a while in the `DESCRIBE` request before sending 
```
[2022-01-10 11:17:29.187] [ServerSession] [trace] Eos. Session: 1
```

Yet, if the camera is brought back up or switched to a different reachable RTSP stream, `ReStreamer` is stuck and must be restarted.

**Comment by RSATom** [comment]
@eslam-ahmed-khair please try the latest version

**Comment by eslam-ahmed-khair** [comment]
Fixed, Thanks!
