### ISSUE TITLE
HTTP Auth

### ISSUE THREAD

**Issue by fuad00** [WebRTSP/ReStreamer#26]
Is it possible to add auth on webpage?

**Comment by RSATom** [comment]
Unfortunately I didn't have time to implement it, and I'm not sure when will have...

**Comment by RSATom** [comment]
I can add some sort of token based auth on WebRTSP protocol level, but I need help with HTML/JS side.

**Comment by RSATom** [comment]
FYI, I'm trying to implement something related... but can't promise how quick it will be...

**Comment by RSATom** [comment]
@fuad00 if you still interested, you can try the latest version (and if you are using snap package, it's required to use `edge` channel). 
To enable auth support you should uncomment following lines in config:
https://github.com/WebRTSP/ReStreamer/blob/f86f6c14d0899cf5e38288fe90cba68e4f0703cc/restreamer.conf.sample#L77-L83

**Comment by RSATom** [comment]
Closing this for now as completed. If there will be any issue - please reopen this, or create new issue...
