### ISSUE TITLE
Stops working randomly after a week or so

### ISSUE THREAD

**Issue by DrJaymz** [WebRTSP/ReStreamer#27]
I run on PI4 and it streams a hik camera to a smart mirror.  Its stops after a period that appears random. I tried to restart it but not sure I did it the right way, reboot fixes it for another 5 to 18 days.

I think today it quit at 10.49 - there is usually stuff in the syslog then it stops at 10.49.  See:

```
Aug 25 08:18:08 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: [2022-08-25 08:18:08.542] [WsServer] [info] Got PLAY request for "124"
Aug 25 08:48:06 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 164:22:00.335800182  3013 0xab98e730 WARN                 rtspsrc gstrtspsrc.c:6585:gst_rtspsrc_send:<source> error: Unhandled error
Aug 25 08:48:06 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 164:22:00.335861978  3013 0xab98e730 WARN                 rtspsrc gstrtspsrc.c:6585:gst_rtspsrc_send:<source> error: Option not supported (551)
Aug 25 08:48:06 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 164:22:00.335933848  3013 0xab98e730 WARN                 rtspsrc gstrtspsrc.c:8669:gst_rtspsrc_pause:<source> error: Could not send message. (Generic error)
Aug 25 08:48:07 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: [2022-08-25 08:48:07.867] [WsServer] [info] Got DESCRIBE request for "124"
Aug 25 08:48:08 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 164:22:01.912510541  3013  0x1d19208 WARN                GST_PADS gstpad.c:4231:gst_pad_peer_query:<nicesrc659:src> could not send sticky events
Aug 25 08:48:08 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 164:22:01.913005019  3013 0xaaf53d18 WARN                GST_PADS gstpad.c:4231:gst_pad_peer_query:<nicesrc658:src> could not send sticky events
Aug 25 08:48:08 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: [2022-08-25 08:48:08.344] [WsServer] [info] Got PLAY request for "124"
Aug 25 09:18:06 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 164:52:00.324595556  3013 0xa9138150 WARN                 rtspsrc gstrtspsrc.c:6326:gst_rtsp_src_receive_response:<source> receive interrupted
Aug 25 09:18:06 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 164:52:00.324652445  3013 0xa9138150 WARN                 rtspsrc gstrtspsrc.c:6424:gst_rtspsrc_try_send:<source> receive interrupted
Aug 25 09:18:06 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 164:52:00.324674537  3013 0xa9138150 WARN                 rtspsrc gstrtspsrc.c:8672:gst_rtspsrc_pause:<source> PAUSE interrupted
Aug 25 09:18:06 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 164:52:00.327414887  3013 0xa9138150 WARN                 rtspsrc gstrtspsrc.c:6585:gst_rtspsrc_send:<source> error: Unhandled error
Aug 25 09:18:06 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 164:52:00.327447794  3013 0xa9138150 WARN                 rtspsrc gstrtspsrc.c:6585:gst_rtspsrc_send:<source> error: Option not supported (551)
Aug 25 09:18:06 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 164:52:00.327514590  3013 0xa9138150 WARN                 rtspsrc gstrtspsrc.c:8096:gst_rtspsrc_close:<source> error: Could not send message. (Generic error)
Aug 25 09:18:07 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: [2022-08-25 09:18:07.900] [WsServer] [info] Got DESCRIBE request for "124"
Aug 25 09:18:08 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 164:52:01.810846881  3013 0xa7d226f8 WARN                GST_PADS gstpad.c:4231:gst_pad_peer_query:<nicesrc660:src> could not send sticky events
Aug 25 09:18:08 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 164:52:01.811126045  3013 0xa9138118 WARN                GST_PADS gstpad.c:4231:gst_pad_peer_query:<nicesrc661:src> could not send sticky events
Aug 25 09:18:08 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: [2022-08-25 09:18:08.203] [WsServer] [info] Got PLAY request for "124"
Aug 25 09:48:06 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 165:22:00.372784375  3013 0xab98e688 WARN                 rtspsrc gstrtspsrc.c:6585:gst_rtspsrc_send:<source> error: Unhandled error
Aug 25 09:48:06 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 165:22:00.372898077  3013 0xab98e688 WARN                 rtspsrc gstrtspsrc.c:6585:gst_rtspsrc_send:<source> error: Option not supported (551)
Aug 25 09:48:06 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 165:22:00.373056187  3013 0xab98e688 WARN                 rtspsrc gstrtspsrc.c:8669:gst_rtspsrc_pause:<source> error: Could not send message. (Generic error)
Aug 25 09:48:08 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: [2022-08-25 09:48:08.161] [WsServer] [info] Got DESCRIBE request for "124"
Aug 25 09:48:08 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 165:22:02.117674539  3013 0xaaf5a900 WARN               rtpsource rtpsource.c:1213:update_receiver_stats: probation: seqnr 17554 != expected 17553 (SSRC 632769145 curr_probation 1 probation 2)
Aug 25 09:48:08 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 165:22:02.117872093  3013 0xaaf5a900 WARN               rtpsource rtpsource.c:1213:update_receiver_stats: probation: seqnr 17553 != expected 17555 (SSRC 632769145 curr_probation 2 probation 2)
Aug 25 09:48:08 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 165:22:02.118031110  3013 0xaaf5a900 WARN               rtpsource rtpsource.c:1213:update_receiver_stats: probation: seqnr 17555 != expected 17554 (SSRC 632769145 curr_probation 2 probation 2)
Aug 25 09:48:10 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 165:22:04.138684108  3013 0xa9b6e848 WARN                GST_PADS gstpad.c:4231:gst_pad_peer_query:<nicesrc662:src> could not send sticky events
Aug 25 09:48:10 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 165:22:04.139091698  3013 0xa912e410 WARN                GST_PADS gstpad.c:4231:gst_pad_peer_query:<nicesrc663:src> could not send sticky events
Aug 25 09:48:10 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: [2022-08-25 09:48:10.578] [WsServer] [info] Got PLAY request for "124"
Aug 25 10:05:51 netcom-pi4 snapd[412]: storehelpers.go:722: cannot refresh: snap has no updates available: "certbot", "core", "core18", "core20", "gotop-brlin", "rtsp-to-webrtsp"
Aug 25 10:18:06 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 165:52:00.364399925  3013 0xab9608b8 WARN                 rtspsrc gstrtspsrc.c:6585:gst_rtspsrc_send:<source> error: Unhandled error
Aug 25 10:18:06 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 165:52:00.364509683  3013 0xab9608b8 WARN                 rtspsrc gstrtspsrc.c:6585:gst_rtspsrc_send:<source> error: Option not supported (551)
Aug 25 10:18:06 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 165:52:00.364670293  3013 0xab9608b8 WARN                 rtspsrc gstrtspsrc.c:8669:gst_rtspsrc_pause:<source> error: Could not send message. (Generic error)
Aug 25 10:18:08 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: [2022-08-25 10:18:08.146] [WsServer] [info] Got DESCRIBE request for "124"
Aug 25 10:18:08 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 165:52:02.046247060  3013 0xa870f3a0 WARN                GST_PADS gstpad.c:4231:gst_pad_peer_query:<nicesrc664:src> could not send sticky events
Aug 25 10:18:08 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 165:52:02.046473224  3013 0xaa57f458 WARN                GST_PADS gstpad.c:4231:gst_pad_peer_query:<nicesrc665:src> could not send sticky events
Aug 25 10:18:08 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: [2022-08-25 10:18:08.526] [WsServer] [info] Got PLAY request for "124"
Aug 25 10:18:08 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 165:52:02.305518931  3013 0xab965810 WARN                 dtlsenc gstdtlsenc.c:386:src_activate_mode:<dtlsenc665> failed to activate pad task
Aug 25 10:18:08 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 165:52:02.305787984  3013 0xab965810 WARN                GST_PADS gstpad.c:1142:gst_pad_set_active:<dtlsenc665:src> Failed to activate pad
Aug 25 10:48:06 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 166:22:00.362575660  3013 0xa9163330 WARN                 rtspsrc gstrtspsrc.c:6585:gst_rtspsrc_send:<source> error: Unhandled error
Aug 25 10:48:06 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 166:22:00.363757855  3013 0xa9163330 WARN                 rtspsrc gstrtspsrc.c:6585:gst_rtspsrc_send:<source> error: Option not supported (551)
Aug 25 10:48:06 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 166:22:00.364151130  3013 0xa9163330 WARN                 rtspsrc gstrtspsrc.c:8669:gst_rtspsrc_pause:<source> error: Could not send message. (Generic error)
Aug 25 10:48:45 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 166:22:39.511458099  3013 0xa9163330 WARN                 rtspsrc gstrtspsrc.c:5637:gst_rtspsrc_loop_udp:<source> warning: Unhandled return value -7.
Aug 25 10:48:45 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 166:22:39.511544746  3013 0xa9163330 WARN                 rtspsrc gstrtspsrc.c:5705:gst_rtspsrc_loop_udp:<source> error: Could not receive message. (System error)
Aug 25 10:48:45 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 166:22:39.511602135  3013 0xa9163330 WARN                 rtspsrc gstrtspsrc.c:6057:gst_rtspsrc_loop:<source> error: Internal data stream error.
Aug 25 10:48:45 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 166:22:39.511621060  3013 0xa9163330 WARN                 rtspsrc gstrtspsrc.c:6057:gst_rtspsrc_loop:<source> error: streaming stopped, reason error (-5)
Aug 25 10:49:12 netcom-pi4 rtsp-to-webrtsp.ReStreamer[3013]: 166:23:06.519050603  3013 0xaaf16040 WARN                 rtspsrc gstrtspsrc.c:3458:on_timeout_common:<source> source 278a6844, stream 278a6844 in session 0 timed out
```

Is there any other debug I can provide that might help?

Failing that how do I restart it?  I could write a bodge script that detect the session 0 timed out and restart it.
I thought it might be `$sudo snap restart rtsp-to-webrtsp`  but that command didn't return until I restarted the box.

**Comment by RSATom** [comment]
`sudo snap restart rtsp-to-webrtsp` definetly should work 🤔 

can you please provide output of `snap version` ?

**Comment by DrJaymz** [comment]
`pi@netcom-pi4:~ $ snap version
snap      2.56.2
snapd     2.56.2
series    16
raspbian  10
kernel    5.10.103-v7l+`

**Comment by RSATom** [comment]
Hm... You definitely have the latest versions... The question is why `restart` hangs... It should be able restart snap even if it has any bug inside... Maybe it worth file a bag to snapd developers...

**Comment by RSATom** [comment]
On my side I'll try to find possible reason of my app hang...

**Comment by RSATom** [comment]
@DrJaymz do you have any older Pi device to test? I can test it myself only on rpi 2 or 3, and curious if problem can be related to Pi version...

**Comment by RSATom** [comment]
It looks like I was able to reproduce... Investigating...

**Comment by DrJaymz** [comment]
> 

what did you do, just leave it running?

**Comment by RSATom** [comment]
yes, with connecting to it time to time...

**Comment by RSATom** [comment]
btw, as temporary workaround you can try to use `kill` to restart process.

**Comment by RSATom** [comment]
@DrJaymz please try the latest version from `edge` channel. I've fixed some issue, but can't be sure it's issue you've met...

**Comment by DrJaymz** [comment]
Will do and let you know.

**Comment by DrJaymz** [comment]
> @DrJaymz please try the latest version from `edge` channel. I've fixed some issue, but can't be sure it's issue you've met...

I have not had the issue for a while and ...

```
pi@netcom-pi4:~ $ sudo snap refresh rtsp-to-webrtsp --edge
snap "rtsp-to-webrtsp" has no updates available
```

Suggests that I may already be up to date?

Although...


```
refresh-date: yesterday at 06:33 BST
channels:
  latest/stable:    15eb047 2022-09-03 (345) 83MB -
  latest/candidate: ↑
  latest/beta:      ↑
  latest/edge:      3f7bdbc 2022-09-19 (351) 83MB -
installed:          3f7bdbc            (351) 83MB -
pi@netcom-pi4:~ $
```


Suggests its not up to date.

**Comment by RSATom** [comment]
`snapd` updates installed snaps to the latest version from the same channel (with some delay about day or so). So yes, you already have the latest patched version installed.

**Comment by DrJaymz** [comment]
in which case I will see how it goes.  Its a smart mirror in the hallway because there's no window in the door so I will soon notice when the feed stops working.

**Comment by RSATom** [comment]
Finally I want use it the same way, but with automatic screen turn on/off by motion detection.

**Comment by RSATom** [comment]
It works without any issue on my test server about a week. Before it was not able to keep working more than day. So I think issue is really fixed. Please reopen if you catch it again...

**Comment by DrJaymz** [comment]
snapped again:

`Sep 27 12:33:23 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: [2022-09-27 12:33:23.230] [WsServer] [info] Got DESCRIBE request for "124"
Sep 27 12:33:23 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 173:32:45.999689725   750 0xafff1f30 WARN                GST_PADS gstpad.c:4231:gst_pad_peer_query:<nicesrc694:src> could not send sticky events
Sep 27 12:33:23 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 173:32:46.000362812   750 0xb1b1b558 WARN                GST_PADS gstpad.c:4231:gst_pad_peer_query:<nicesrc695:src> could not send sticky events
Sep 27 12:33:23 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: [2022-09-27 12:33:23.490] [WsServer] [info] Got PLAY request for "124"
Sep 27 12:45:38 netcom-pi4 snapd[31838]: storehelpers.go:748: cannot refresh: snap has no updates available: "certbot", "core", "core18", "core20", "gotop-brlin", "rtsp-to-webrtsp"
Sep 27 13:03:22 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:02:45.199197002   750 0xaffcaf60 WARN                 rtspsrc gstrtspsrc.c:6326:gst_rtsp_src_receive_response:<source> receive interrupted
Sep 27 13:03:22 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:02:45.199254891   750 0xaffcaf60 WARN                 rtspsrc gstrtspsrc.c:6424:gst_rtspsrc_try_send:<source> receive interrupted
Sep 27 13:03:22 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:02:45.199277335   750 0xaffcaf60 WARN                 rtspsrc gstrtspsrc.c:8672:gst_rtspsrc_pause:<source> PAUSE interrupted
Sep 27 13:03:22 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:02:45.202057277   750 0xaffcaf60 WARN                 rtspsrc gstrtspsrc.c:6585:gst_rtspsrc_send:<source> error: Unhandled error
Sep 27 13:03:22 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:02:45.202089554   750 0xaffcaf60 WARN                 rtspsrc gstrtspsrc.c:6585:gst_rtspsrc_send:<source> error: Option not supported (551)
Sep 27 13:03:22 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:02:45.202163998   750 0xaffcaf60 WARN                 rtspsrc gstrtspsrc.c:8096:gst_rtspsrc_close:<source> error: Could not send message. (Generic error)
Sep 27 13:03:23 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: [2022-09-27 13:03:23.552] [WsServer] [info] Got DESCRIBE request for "124"
Sep 27 13:03:23 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:02:46.319833800   750   0xaac6a8 WARN               rtpsource rtpsource.c:1213:update_receiver_stats: probation: seqnr 21566 != expected 21565 (SSRC 2090345459 curr_probation 1 probation 2)
Sep 27 13:03:23 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:02:46.320455165   750   0xaac6a8 WARN               rtpsource rtpsource.c:1213:update_receiver_stats: probation: seqnr 21565 != expected 21567 (SSRC 2090345459 curr_probation 2 probation 2)
Sep 27 13:03:23 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:02:46.320912551   750   0xaac6a8 WARN               rtpsource rtpsource.c:1213:update_receiver_stats: probation: seqnr 21567 != expected 21566 (SSRC 2090345459 curr_probation 2 probation 2)
Sep 27 13:03:25 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:02:48.332149768   750 0xb115a210 WARN                GST_PADS gstpad.c:4231:gst_pad_peer_query:<nicesrc697:src> could not send sticky events
Sep 27 13:03:25 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:02:48.333449518   750 0xae915760 WARN                GST_PADS gstpad.c:4231:gst_pad_peer_query:<nicesrc696:src> could not send sticky events
Sep 27 13:03:25 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: [2022-09-27 13:03:25.917] [WsServer] [info] Got PLAY request for "124"
Sep 27 13:03:25 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:02:48.593309538   750 0xb11dc688 WARN                 dtlsenc gstdtlsenc.c:386:src_activate_mode:<dtlsenc697> failed to activate pad task
Sep 27 13:03:25 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:02:48.594252457   750 0xb11dc688 WARN                GST_PADS gstpad.c:1142:gst_pad_set_active:<dtlsenc697:src> Failed to activate pad
Sep 27 13:33:22 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:32:45.103981544   750 0xb2f3d320 WARN                 rtspsrc gstrtspsrc.c:6585:gst_rtspsrc_send:<source> error: Unhandled error
Sep 27 13:33:22 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:32:45.104050784   750 0xb2f3d320 WARN                 rtspsrc gstrtspsrc.c:6585:gst_rtspsrc_send:<source> error: Option not supported (551)
Sep 27 13:33:22 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:32:45.104154376   750 0xb2f3d320 WARN                 rtspsrc gstrtspsrc.c:8669:gst_rtspsrc_pause:<source> error: Could not send message. (Generic error)
Sep 27 13:34:01 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:33:24.234922581   750 0xb2f3d320 WARN                 rtspsrc gstrtspsrc.c:5637:gst_rtspsrc_loop_udp:<source> warning: Unhandled return value -7.
Sep 27 13:34:01 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:33:24.235053468   750 0xb2f3d320 WARN                 rtspsrc gstrtspsrc.c:5705:gst_rtspsrc_loop_udp:<source> error: Could not receive message. (System error)
Sep 27 13:34:01 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:33:24.235153820   750 0xb2f3d320 WARN                 rtspsrc gstrtspsrc.c:6057:gst_rtspsrc_loop:<source> error: Internal data stream error.
Sep 27 13:34:01 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:33:24.235192004   750 0xb2f3d320 WARN                 rtspsrc gstrtspsrc.c:6057:gst_rtspsrc_loop:<source> error: streaming stopped, reason error (-5)
Sep 27 13:34:30 netcom-pi4 rtsp-to-webrtsp.ReStreamer[750]: 174:33:53.074894431   750 0xb2f35470 WARN                 rtspsrc gstrtspsrc.c:3458:on_timeout_common:<source> source 7c9823f3, stream 7c9823f3 in session 0 timed out
`

**Comment by RSATom** [comment]
@DrJaymz According to log it's something with our IP Cam. Did you try refresh (with F5) your browser? And did it get working after refresh?

**Comment by DrJaymz** [comment]
The mirror has no keyboard but does restart at night.  It does display ok today.  However I also restarted the snap, so can't tell which did the trick.

**Comment by RSATom** [comment]
@DrJaymz Can you please do following next time you get it stuck:
1. Try access `rtsp-to-webrtsp` from some other PC, and check if it working (without restarting mirror).
2. Restart only mirror and check if it will start working.

I need to understand if it server side problem, or browser client problem....

**Comment by DrJaymz** [comment]
ok, will keep an eye on it.

If the camera were to disappear briefly during streaming (which I would guess is common especially if they were on Wi-Fi which mine are not) - how would recovery take place?  My thinking is that you'd probably need to restart the client, that would then connect to the streamer which would start a fresh stream?

So, its probably the client that needs to timeout and then retry.  Thats going to be the only way to make a hands free system that recovers.  However, I'm sure I navigated to the streamer with chrome and it just game be the wheel suggesting that a new client connection doesn't necessarily fix the problem.

Now, I know exactly what to look for I will specifically check for that.  I could perhaps grep the syslog and find quicker where it goes wrong.

**Comment by RSATom** [comment]
By current design if ReStreamer detects any problem it just closes WebSockets connection to browser (I just decided to simplify my life a little bit by deciding to not implement full errors handling through API when project was started) and browser client tries to create the new connection with 3 seconds timeout.

So here can be following problems:
1. ReStreamer doesn't detect problem with IP Cam by some reason and doesn't close WebSocket connection and browser client doesn't try start new connection.
2. Reconnect logic in browser client just broken in some cases.

**Comment by RSATom** [comment]
It looks like issue is fixed, at least I don't see it on my demo server anymore... If you still see issue, please create new or reopen this issue.
