### ISSUE TITLE
change storage location

### ISSUE THREAD

**Issue by bj97301** [WebRTSP/ReStreamer#28]
I have an external storage that I would like to use.  Is it possible to configure the storage location?

**Comment by RSATom** [comment]
I don't understand, storage location for what? It doesn't save any files...

**Comment by bj97301** [comment]
Shit. Thought so. Was hoping to use it with my cam for a local storage. Thanks though.

**Comment by RSATom** [comment]
I have in my plans to implement recording on motion, but don't know when it will be ready....

**Comment by bj97301** [comment]
I think I need something like openrtsp.

**Comment by bj97301** [comment]
> 

That would be pretty cool. I wish the cam could send a record signal to tell the stream when to record. My cams have ai face detection to trigger recording along with a bunch of other settings. I thought it would be easy to hook the cams up to a pi nas but it's turning out to be much more involved than I expected.  I blame eufy.
