### ISSUE TITLE
Gstreamer RTSP server streams jitter in ReStreamer

### ISSUE THREAD

**Issue by eslam-ahmed-khair** [WebRTSP/ReStreamer#29]
Hi RSATom,

I am using Gstreamer RTSP server 1.16, an example would be like [this](https://github.com/GStreamer/gst-rtsp-server/blob/1.16/examples/test-mp4.c). I noticed that any streams generated by Gstreamer RTSP server that are passed to the `ReStreamer App` stall and cause jittery play-back effect. Any idea how to fix it?

Thanks in advance,
Eslam

**Comment by RSATom** [comment]
Are you sure it produces baseline profile h264 stream?

**Comment by eslam-ahmed-khair** [comment]
yes, in fact it's coming from an ONVIF complaint IP camera. Here's the launch command for the media factory that doesn't work:

`gst_rtsp_media_factory_set_launch(
        factory, ("( "
                  "uridecodebin uri=rtsp://admin:admin@192.168.0.201/defaultPrimary?streamType=u  caps=video/x-h264 ! "
                  "h264parse config-interval=-1 ! metamux ! rtpgstpay name=pay0 pt=96 )"));`
                
`metamux` is a plugin that adds metadata on the byte-level of the stream. likewise, there exists `metademux` that reverses the previous operation and produces baseline h264 which is untouched.

Not that `ReStreamer App` works fine if remove `metamux` and replace `rtpgstpay` with `rtph264pay`. Any hints

**Comment by eslam-ahmed-khair** [comment]
I think it's related to the timestamping of the buffers done by`metademux`. What strategy would you suggest to use to timestamp those h264/h265 buffers after removing the metadata from the byte stream?

**Comment by RSATom** [comment]
Sorrry, I don't know answer...

**Comment by eslam-ahmed-khair** [comment]
Thanks for your help. I'll delete this issue shortly.
