### ISSUE TITLE
H265 Supported ?

### ISSUE THREAD

**Issue by EmpireofKings** [WebRTSP/ReStreamer#3]
Hello,

Thank you @RSATom you are absolutely amazing, this is a wonderful repository. 

I recently tried using restreamer with an H265 camera feed, and was not able to get the feed to play in the browser. 

Is this to due with the javascript client ? or do we need to modify the RTSP parser on the server end ?

Thank you

**Comment by RSATom** [comment]
The main purpose of this project to do restreaming without transcoding (i.e. with minimal CPU load). If modern browsers support h265 codec - then I could add support of such feeds. If not - it will require transcoding and will require big amount of CPU power on server to do realtime transcoding. But anyway, I could add support for that if you are sure could provide enough CPU power.

**Comment by EmpireofKings** [comment]
I agree, transcoding the stream back to H264 would be very inefficient, and by no means ideal. 

According to [this](https://videojs.com/html5-video-support/), there are three major browsers that support H265. 

1. Internet Explorer
2. Microsoft Edge 
3. Safari

I think its never a bad thing to get ahead of the curve, i don't know of many webrtc projects that support H265, but i think this one should.

If you need any assistance, i'd like to throw my hat in the ring and help you.

**Comment by RSATom** [comment]
Ok, I'll look what I can do with it, after will finish some optimizations of restreaming logic.

**Comment by EmpireofKings** [comment]
Awesome take your time, there's no rush.

You might find it interesting to see that the Janus project recently did some work with H265 and AV1.

Here's the relevant [PR](https://github.com/meetecho/janus-gateway/pull/2120)
