### ISSUE TITLE
Safari Browser Support on iOs

### ISSUE THREAD

**Issue by SzymonWojewodzki** [WebRTSP/ReStreamer#32]
Hello,
Do you have any solution why stream is not working on safari?

**Comment by RSATom** [comment]
What OS? Mac OS or iOs or iPad Os? If Mac OS, did you try the same on Chrome?

**Comment by SzymonWojewodzki** [comment]
It does not work on iOs

**Comment by RSATom** [comment]
Confirmed, It doesn't work on iOs for me too. I'll look. Thanks!

**Comment by RSATom** [comment]
Tried on iPhone with iOs 17.5.1 and it works now...
