### ISSUE TITLE
WebRTSP + HTML5 or JSMpeg Player(TS Player) - Samsung Tizen

### ISSUE THREAD

**Issue by michalfordonski** [WebRTSP/ReStreamer#34]
WebRTSP is great. On my raspbery Pi 2 it works much better than ffmpeg. Is it possible to connect an image feed directly from WebRTSP to HTML 5 (VIDEO) or JSMpeg Player(TS Player)? I would like to connect using an application written for a Samsung TV with the Tizen system, which supports HTML+JS+CSS applications - but it has its own requirements that prevent the use of your html with the PIP function on the TV. Is it possible somehow instead of through port 5080 to get to a direct signal that would be handled by HTML5 or JSMpeg?

Example HTML5 code from VIDEO is:
[LINK](https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_video)

JSMpeg Player(TS Player):
[LINK](https://www.npmjs.com/package/jsmpeg-player)

Another solution that works, but video performance on raspberry 2 is poor.
[LINK](https://github.com/vzakharchenko/rtsp-samsung-tv)

I tried with the snippets below - unfortunately I was unable to connect WebRTSP to them.

```
<div id="videoWrapper"></div>
<script src="https://cdn.jsdelivr.net/npm/jsmpeg-player@3/build/jsmpeg-player.min.js"></script>
<script>
  new JSMpeg.VideoElement('#videoWrapper', 'ws://192.168.1.202:5554');
</script>
```

```
<script type="text/javascript" src="jsmpeg.min.js"></script>
<canvas id="canvas"/>
<script type="text/javascript">
  var url = 'ws://192.168.1.202:5554';
  new JSMpeg.Player(url, {
    canvas: document.getElementById('canvas')
  });
</script>
```

```
<video width="400" controls>
  <source src="http://192.168.1.202:5554/" type="video/mp4">
</video>
```

**Comment by RSATom** [comment]
@michalfordonski there are some questions here:
Is your Tizen device support WebRTC?
Is your Tizen device support WebSockets?
Is your Tizen device support h264 codec?

**Comment by RSATom** [comment]
I've looked at Tizen docs quickly and it looks like all above is supported. Also, [WebRTSP browser client](https://github.com/WebRTSP/BrowserClient) uses HTML5 video element to render video (ReStreamer uses it internally). So it looks like everything is doable.

**Comment by michalfordonski** [comment]
@RSATom Ok, but what does index.html look like from the server to the TV? A copy of the folder containing www with the project was not enough. I changed the url in the index file (lines 15 and 17) giving the server IP instead of ${window.location.hostname} and unfortunately it doesn't work on a laptop or TV. I'm going to try to change it today. Should I set the server IP somewhere else so that the html is on a different device than the server? Additionally, can I set the size of the generated image somewhere? My RTSP signal after processing has extra gray bars on the left and right - I assume that WebRTSP adds them due to resolution matching. Can I disable it somewhere in the configuration?

**Comment by RSATom** [comment]
@michalfordonski I don't understand, where you want to place html files? Do you want to place it directly to application on Tizen device (i.e. it will open it as local files) or you want open it from remote HTTP server?

Also, did you try open link to installed ReStreamer inside browser on your Tizen device?

> Additionally, can I set the size of the generated image somewhere?

You can't incoming stream will always has the same size as ip cam streaming. ReStreamer doesn't do any transcoding since it's too heavy.

> My RTSP signal after processing has extra gray bars on the left and right - I assume that WebRTSP adds them due to resolution matching. Can I disable it somewhere in the configuration?

No, it restreams video without any change. The same here - adding anything to stream will require transcoding, and it's too heavy task.

So anything around video is coming from html or css, nothing else. If you need some different UI you need to change [index.html](https://github.com/WebRTSP/www/blob/master/index.html) or/and [css/WebRTSP.css](https://github.com/WebRTSP/www/tree/master/css/WebRTSP.css)

**Comment by michalfordonski** [comment]
@RSATom 
To run picture-in-picture on a TV, the index.html file needs to be on the device, so the index.html file that is normally on the server needs to be moved to the app on Tizen.

> Also, did you try open link to installed ReStreamer inside browser on your Tizen device?

Yes, it works, but it cannot be enabled in Picture In Picture mode.

> So anything around video (or video size) is coming from html or css, nothing else. If you need some different UI you need to change [index.html](https://github.com/WebRTSP/www/blob/master/index.html) or/and [css/WebRTSP.css](https://github.com/WebRTSP/www/tree/master/css/WebRTSP.css)

Ok, in that case I will look for the relevant fragments there.

**Comment by RSATom** [comment]
> To run picture-in-picture on a TV, the index.html file needs to be on the device, so the index.html file that is normally on the server needs to be moved to the app on Tizen.

Now I see... Then there possible some restrictions on Tizen level on connecting to external WebSockts server from local .html files. Maybe some additional configuration is required on server side - don't know. Is it possible to get access JS logs on that device?

**Comment by michalfordonski** [comment]
The problem is probably the modular structure of the client. I tried to convert it so that instead of mjs there were js, but I think I messed something up, because I have:

Connecting to ws://192.168.1.202:5554/...
WebRTSP.js:302 Connected.
WebRTSP.js:344 Disconnected.

I'm testing locally on Google Chrome.

Link: [https://files.fm/u/qywqjtgag](https://files.fm/u/qywqjtgag)

**Comment by RSATom** [comment]
I think the simplest way to convert mjs to js will be using something like webpack (or don't know what is popular these days)

**Comment by michalfordonski** [comment]
Thank you for the suggestion. I've heard of webpack before, but I haven't worked with it. I installed, tried plugging and generating, but I'm probably doing something wrong when setting up/running the project. Could you generate such a file and put it on github or send it to me?

**Comment by RSATom** [comment]
Unfortunately I'm more from C++ world than from JS world... And I never used Webpack (or any other similar tool) myself. Just know it exists and know some thing it can do...

**Comment by RSATom** [comment]
What about this question?

> Is it possible to get access to JS logs on that device?

**Comment by RSATom** [comment]
@michalfordonski please try put following into your `www`:
https://github.com/WebRTSP/www/blob/webpack/index.html
https://github.com/WebRTSP/www/blob/webpack/WebRTSP.js

P.S. It's my first experience with WebPack so don't know how well it will work. But at least I was able to see video on my dev host with above files.

**Comment by michalfordonski** [comment]
Thank you, it works.
