### ISSUE TITLE
Embed web client into snap package

### ISSUE THREAD

**Issue by sam-cmyk** [WebRTSP/ReStreamer#35]
I am trying to embed my own webpage into the snap package because I cannot use the source files because of hardware limitations(Ubuntu 18.04) and the only thing that seems to work is the `rtsp-to-webrtsp-snap` package. I was wondering if there is any other way than developing my own snap application to embed the webpage of my choice? 

Any suggestions are welcomed! Thanks a lot!

**Comment by RSATom** [comment]
I'm thinking about add ability put custom `www` files near config file and add related option into config.
Then there will be no need to create separate snap to get custom UI.

**Comment by sam-cmyk** [comment]
Woah! That will be really great, thank you so much!

**Comment by sam-cmyk** [comment]
Okay, that should not be a problem. This is really nice and helpful of you, thanks!

**Comment by RSATom** [comment]
@sam-cmyk you can try snap package from `edge` channel.
You will need to change `www-root` in [config file](https://github.com/WebRTSP/ReStreamer/blob/84aef63242b82a0b412e3c2e6bf7bb8c297d6b3e/restreamer.conf.sample#L13)
