### ISSUE TITLE
User name and password visible on hover over button

### ISSUE THREAD

**Issue by BjoernM85** [WebRTSP/ReStreamer#36]
When you hover over the buttons for each stream/camera and you use an url for rtsp stream in format rtsp://<username>:password@..., then you can see this url.
In my opinion it is an security problem.
It would be better to add a description property in config for each cam which is shown on hover.

**Comment by RSATom** [comment]
@BjoernM85 it already exists https://github.com/WebRTSP/ReStreamer/blob/master/restreamer.conf.sample#L19
and `url` never sending to client, only `description`
