### ISSUE TITLE
Links for the individual streams?

### ISSUE THREAD

**Issue by HeavyD1710** [WebRTSP/ReStreamer#39]
Hello,
what are the links for the individual streams. I want to paste this into my own website.
Best regards Dirk

**Comment by RSATom** [comment]
Do you mean you want use that "link for individual stream" in regular HTML5 video element? Or something else?

**Comment by HeavyD1710** [comment]
I would like to display the streams in a Smarthome VIS (visualization).  This runs in a browser (e.g. Chrome, kiosk browser).

**Comment by RSATom** [comment]
Then you have to implement custom browser client with your own UI and logic. You can use https://github.com/WebRTSP/www as starting point.

**Comment by RSATom** [comment]
@HeavyD1710 FYI, now it's possible view only specific streamer. You can use something like
http://ipcam.stream:5080/v/%C5%A0trbsk%C3%A9%20pleso

i.e. http(s)://your_server:5080/v/your_streamer_name
