### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by skem5** [WebRTSP/ReStreamer#4]
Hi @RSATom ,

Firstly, this is amazing and it really serves my application perfectly. I did get into an issue trying to run the service on https. Is there a configuration that can be enabled for this functionality? I also tried to use a proxy get and what happened with that is you could get to server but it would not start the stream to the camera. Have you tried running it on https instead of http? Is it even possible?
Thanks again and avegoodone.

**Comment by EmpireofKings** [comment]
I've used it with https.

Look at main.cpp and WsServer.cpp for more details.

You'll need to pass an SSL certificate to the config file, and if you're using different ports for the secure websockets you need to change config.js to match.

**Comment by skem5** [comment]
Thanks @EmpireofKings. I couldn't find any details in WsServer.cpp on how to set it up. Do you have a copy of the Config.js that you used when you gave it a go?

**Comment by RSATom** [comment]
I would recommend you use something like NGINX as frontend to get HTTPS support. You could look to https://github.com/WebRTSP/SignalingServer/blob/master/enableSSL.sh as example how it can be configured.

**Comment by RSATom** [comment]
@skem5 But if you still want add HTTPS support without NGINX you will need to add following lines to your config:
```
secure-port: <port-for-https-connections>
certificate: "path/to/tls/certificate"
key: "path/to/private/key"
```

**Comment by RSATom** [comment]
I've tried to make [config a little bit more clear ](https://github.com/WebRTSP/ReStreamer/blob/master/restreamer.conf.sample), please check.

**Comment by skem5** [comment]
Hi @RSATom 

Thanks for all your help with this. I am not sure if I am doing something wrong. Here is the config that I am using:
[restreamer.conf.txt](https://github.com/WebRTSP/ReStreamer/files/7028396/restreamer.conf.txt)

Here is what I get if I run the snap logs:
![image](https://user-images.githubusercontent.com/89295954/130375086-24571a45-73d9-4d74-98d5-7cb3a1e9d2fc.png)
 When I try to use a proxy with this redirect:
![image](https://user-images.githubusercontent.com/89295954/130375145-7cebbdaf-c48f-47aa-9078-68c65104c781.png)
 I can get to the web page but the stream never starts playing.

**Comment by RSATom** [comment]
@skem5 The main problem with snap package - it doesn't have access to files on your system. There are only few dirs [snap package can access](https://snapcraft.io/docs/environment-variables). So you have to copy certificate/key files to some of them. I would recommend try put certificate/key near the config file.

What about NGINX configuration - you should proxy both HTTP and WS connections (i.e. 5080 and 5554 ports) and also some other ports should be opened (I didn't investigate yet what exactly ports range GStreamer uses for WebRTC streaming) to have ability to do UDP streaming.

**Comment by RSATom** [comment]
And I think https://github.com/WebRTSP/SignalingServer/blob/master/enableSSL.sh is not correct, so it was bad advice to use it, sorry. I'll try to prepare valid one soon.

**Comment by RSATom** [comment]
@skem5 I've prepared another script for configuring NGINX: https://github.com/WebRTSP/ReStreamer/blob/master/enableSSL.sh please try.
Usage example: `./enableSSL.sh root@your_ssh_server.com your_email@examplel.com`

**Comment by skem5** [comment]
@RSATom Thanks for this. I haven't given the new script a go, there is just something I need to sort out on the server before i change the port forward on my router. I will let you know how it goes.

**Comment by RSATom** [comment]
@skem5  TBH I don't like an idea about port forwarding... Can you please share what exactly you are trying to build?

**Comment by skem5** [comment]
Hi @RSATom ,
Sorry it took me a while to get back to test this. I was finally able to test it today. So i run the nginx script you sent and it does the same thing. It gets to the page but it does not load the stream. It gets stuck here:
![image](https://user-images.githubusercontent.com/89295954/131809188-8bda6356-3e77-4708-8ec2-efa6e492e05c.png)

Oh, and - the port forwarding was just for cerbot. Essentially i have a linux machine on a local network connected to a IP camera and I am trying to stream the camera on localhost using https. Http works just fine - its the https that is not working.

**Comment by RSATom** [comment]
@skem5 so you IP cam, linux host and client host are all on the same local network, right?

**Comment by skem5** [comment]
Yes.

**Comment by RSATom** [comment]
Can you please show messages from JS Console? I think browser could not connect to server over wss.

**Comment by skem5** [comment]
Hi @RSATom,
You're right. Here is the JS Console output:
![image](https://user-images.githubusercontent.com/89295954/132085651-95ba1a49-be7b-42dc-a647-b904c7dd603d.png)
![image](https://user-images.githubusercontent.com/89295954/132085659-f526f892-c031-4b54-964a-a0bc88da5691.png)

**Comment by RSATom** [comment]
@skem5
1. 10.194.67.100 is private network IP, don't think you was able create Certificate for it.
2. You have to use your domain name you've used to issue Certificate to be able access your server with https/wss

**Comment by skem5** [comment]
@RSATom, domain would just be semantics. I get the same issue using the domain name:
![image](https://user-images.githubusercontent.com/89295954/132090095-83c61111-e789-4751-9dfc-df955d7987f4.png)

Using http would output this, for reference:
![image](https://user-images.githubusercontent.com/89295954/132090130-0712a84b-bd3b-4d83-8dc9-3752bf3bde33.png)

**Comment by RSATom** [comment]
Did you configure port forwarding for 5555 port on your router?

**Comment by RSATom** [comment]
According to nslookup your domain points to private network IP (`10.194.67.100`). So I still can't understand how you was able to create Certificate for that domain with certbot, since it requires real public IP...

**Comment by RSATom** [comment]
@skem5 do you have static IP on WAN port of your router?

**Comment by EmpireofKings** [comment]
Hey guys,

if you're connecting to the wss port you'll need to change your config.js to also point to 5443. (or whatever nginx is listening on)

Nginx will proxy the request, and pass allow the connection to complete.

[reference:](https://stackoverflow.com/questions/51971774/ssl-websockets-with-nginx-cannot-connect)

**Comment by EmpireofKings** [comment]
My nginx conf looks like this :

`server {
	listen 5443 ssl http2 default_server;
	listen [::]:5443 ssl http2 default_server;

        include snippets/snakeoil.conf;

	server_name  $TARGET_DOMAIN;

	location / {
        proxy_pass http://0.0.0.0:5080/;
        proxy_pass ws://0.0.0.0:5554/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_buffering off;
        proxy_http_version 1.1;
        }

       location = /Config.js {
          proxy_pass http://0.0.0.0:5080/Config.js;
          sub_filter 'const WebRTSPPort = 5554;' 'const WebRTSPPort = 5555;';
          sub_filter_types  text/html text/javascript application/json;
          sub_filter_once off;
        }

	# deny access to .htaccess files, if Apache's document root
	# concurs with nginx's one
	#
	#location ~ /\.ht {
	#	deny all;
	#}

       # also check mimetypes @ /etc/nginx/mime.types
}`

**Comment by RSATom** [comment]
@EmpireofKings you are right, and [enableSSL.sh](https://github.com/WebRTSP/ReStreamer/blob/master/enableSSL.sh#L61) already takes it into the account

**Comment by skem5** [comment]
Hi @RSATom , I do have a public IP. I was trying it with the public IP and then i change the DNS entry after i was done. @EmpireofKings  thanks for that addition. I will try to have it use ws instead of wss and see what outcome that produces.

**Comment by RSATom** [comment]
I think I've got what you trying to do:
1. You've used your router's public IP to get Certificate/Private key
2. After that you've replaced your public IP with your private IP to be able use mentioned above Certificate/Key on local network.

So, can you please show me what you get if open https://remotesite1cam.engineeringinsights.com.au:5555/ in your browser?

**Comment by skem5** [comment]
This is what i get in my browser:
![image](https://user-images.githubusercontent.com/89295954/132144700-331bcf45-a497-45eb-8228-343f1e9c8573.png)

**Comment by RSATom** [comment]
This means you have cert/key configured correctly, but it's stillsomething wrong with nginx config. You should get 404 error in this case. For example: https://ipcam.stream:5555/
Is it possible you didn't delete your original nginx config before run `enableSSL.sh` ?

**Comment by skem5** [comment]
Hi @RSATom , I still get error 403. I am not sure why. Here is my nginx conf, may be might see something that i missed.
[rtsp-to-webrtsp.conf.txt](https://github.com/WebRTSP/ReStreamer/files/7117984/rtsp-to-webrtsp.conf.txt)

**Comment by EmpireofKings** [comment]
@skem5 

Change

```
   proxy_pass http://localhost:5554/;

```
To

 ```
   proxy_pass ws://0.0.0.0:5554/;

```

**Comment by skem5** [comment]
@EmpireofKings , I tried that and i got this error from nginx
![image](https://user-images.githubusercontent.com/89295954/132268865-ed4083c6-aeb7-484c-9a56-3e82be05f8d3.png)

**Comment by skem5** [comment]
Oh, man...i'm an idiot.
When i was looking at the like above I realized i left the print exception on the proxy_set_header Upgrade. Got it working now.
@RSATom and @EmpireofKings , you guys are legends! I owe each of you a coffee

**Comment by RSATom** [comment]
@skem5 Don't sure understand what exactly problem you had, but anyway I'm glad you've got it working. Please close this issue if you haven't any related questions anymore.
