### ISSUE TITLE
mDNS ice candidates from Chrome and Firefox

### ISSUE THREAD

**Issue by EmpireofKings** [WebRTSP/ReStreamer#5]
Hello again,

It seems that one needs to disable the flag

chrome://flags/#enable-webrtc-hide-local-ips-with-mdns

in chrome and firefox to prevent these this warning from arising.

```
** (<unknown>:11495): WARNING **: 16:17:38.480: (gstdtlsconnection.c:531):gst_dtls_connection_process: runtime check failed: (!priv->bio_buffer)
```

I'm not sure what causes this one though, the below warning seems to cause connection problems after a while.

```
** (<unknown>:11495): WARNING **: 16:17:17.120: Error deleting port mapping: See UPnP Device Architecture section on Control.
```
I saw you implemented a basic work around [here](https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/issues/1139) :

I'm guessing something has changed which is why the warnings pop up again.

**Comment by RSATom** [comment]
Thanks! I'll investigate.

**Comment by EmpireofKings** [comment]
Though it would be helpful to provide some background on the second warning, so here you go:

I'm running restreamer on a subnet 192.168.0.15, and connecting to it from a browser on a different subnet 192.168.1.15

When the i close the browser window or move to a different page is when this warning pops up.

`** (<unknown>:11495): WARNING **: 16:17:17.120: Error deleting port mapping: See UPnP Device Architecture section on Control.`

After about 10 minutes or so, restreamer (libwebsockets) will refuse to connect to a new client. 

It seems to me its the browser client not closing the connection properly, but it could be the websocketserver itself.

I've only experienced this issue when restreamer is running from a subnet.

**Comment by RSATom** [comment]
@EmpireofKings I didn't fully investigate your issue yet, but did update libwebsockets to the latest stable version. Can you please check if you are able to reproduce connect refusing now?

**Comment by RSATom** [comment]
one else system handle leak should be fixed now...

**Comment by eslam-ahmed-khair** [comment]
Hello, 

I think it's more stable now. What I don't understand is how your referenced commit fixed it?

you simply made `~GstStreamingSource()` additionally call `reset()` on the tee, fakesink and the pipeline itself. then added setting the pipeline' state to `NULL` later.  I mean if those were causing a leak, we should have seen them by `GST_TRACER`.

**Comment by RSATom** [comment]
@eslam-ahmed-khair The same `GstStreamingSource` can be reinitialized multiple times (when all clients leave and some client attaches again later to cleaned instance), and bus watch can be added multiple times, but before that patch bus watch was removed only once (in destructor). And now bus watch removing on every cleanup.
And it's GSource leak (i.e. inside GLib), not GStreamer.

**Comment by RSATom** [comment]
I hope your issue was resolved, if not - please reopen it.
