### ISSUE TITLE
Accessing stream from a Public address via router

### ISSUE THREAD

**Issue by skem5** [WebRTSP/ReStreamer#9]
Hi,

Here is something that i am having a bit of trouble with. I am trying to access this stream from a public domain like this:
![image](https://user-images.githubusercontent.com/89295954/136115863-e7e60cfb-b024-4430-982a-6f9b681d4034.png)

What i am noticing is that the connection is made but the stream does not start.
![image](https://user-images.githubusercontent.com/89295954/136116047-67cb96c0-bdf3-4908-952e-3440190e2340.png)

I suspect that this may be because the service is responding with its local IP address in the Application Data which is causing the client to try and make the STUN bind with the local address instead of the public address. The wireshark capture shows this:
![image](https://user-images.githubusercontent.com/89295954/136116525-1b3129a6-eab9-4779-ad3e-c1c22d8ef8ca.png)
![image](https://user-images.githubusercontent.com/89295954/136116585-b559d990-314e-439c-b17d-0a87783bc9ee.png)

And because the address is local it can never be resolved at the client end. Is there a configuration solution to this?

**Comment by RSATom** [comment]
Does "Netflow Collector" has public IP?

**Comment by skem5** [comment]
hi @RSATom ,
What do you mean by "Netflow Collector"?

**Comment by RSATom** [comment]
@skem5 It's on your first screen.

**Comment by RSATom** [comment]
The main idea is if both WebRTC client and server are behind NAT - you have to use TURN server.

**Comment by RSATom** [comment]
I hope your issue was resolved, if not - please reopen it.
